version: '3.3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:5.0.9-buster
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
  nginx:
    image: jeffreyca/spleeter-web-nginx:latest
    volumes:
      - staticfiles:/webapp/staticfiles
    depends_on:
      - api
    restart: always
  api:
    image: jeffreyca/spleeter-web-api:latest
    volumes:
      - assets:/webapp/frontend/assets
      - staticfiles:/webapp/staticfiles
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - APP_HOST
      - YOUTUBE_API_KEY
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
      - AZURE_CONTAINER
    depends_on:
      - db
      - redis
      - frontend
    restart: always
  frontend:
    image: jeffreyca/spleeter-web-frontend:latest
    volumes:
      - assets:/webapp/frontend/assets
    stdin_open: true
    tty: true
  celery:
    image: jeffreyca/spleeter-web-celery:latest
    entrypoint: ./celery-entrypoint.sh
    volumes:
      - pretrained-models:/webapp/pretrained_models
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - APP_HOST
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
      - AZURE_CONTAINER
      - CELERY_WORKER_CONCURRENCY
    depends_on:
      - db
      - redis
    restart: always
volumes:
  pg-data:
  redis-data:
  pretrained-models:
  assets:
  staticfiles:
