version: '3.3'
services:
  nginx:
    volumes:
      - /path/to/media:/webapp/media
  api:
    volumes:
      - /path/to/media:/webapp/media
  celery:
    volumes:
      - /path/to/media:/webapp/media
