name: Docker Compose push (master)

on:
  push:
    branches: [ v3 ]
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-cpu:
    name: Build and publish CPU images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_TOKEN }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Free disk space
      run: sudo rm -rf /usr/local/lib/android "$AGENT_TOOLSDIRECTORY"

    - name: Build images (v3)
      run: docker compose -f docker-compose.yml -f docker-compose.build.yml build

    - name: Push images to Docker Hub (v3)
      run: docker compose -f docker-compose.yml -f docker-compose.build.yml push
      env:
        DOCKER_CLIENT_TIMEOUT: 180
        COMPOSE_HTTP_TIMEOUT: 180

  build-gpu:
    name: Build and publish GPU images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_TOKEN }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Free disk space
      run: sudo rm -rf /usr/local/lib/android "$AGENT_TOOLSDIRECTORY"

    - name: Build GPU images (v3)
      run: docker compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml build api

    - name: Push GPU images to Docker Hub (v3)
      run: docker compose -f docker-compose.gpu.yml -f docker-compose.build.gpu.yml push api
      env:
        DOCKER_CLIENT_TIMEOUT: 180
        COMPOSE_HTTP_TIMEOUT: 180
